In [16]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [3]:
vectorizer = TfidfVectorizer()

In [15]:
a = vectorizer.fit_transform(['Machine learning is a vast field', 'Machine learning'])
a.toarray()

array([[0.49922133, 0.49922133, 0.35520009, 0.35520009, 0.49922133],
       [0.        , 0.        , 0.70710678, 0.70710678, 0.        ]])

In [9]:
cosine_similarity(a, a)

array([[1.        , 0.50232878],
       [0.50232878, 1.        ]])

In [1]:
d = {
    'hell' : True,
    'hola' : True
}

In [3]:
l = ['hell', 'hola', 'mohja']
nel = list(map(lambda x: d.get(x) if d.get(x) is not None else False, l))
nel

[True, True, False]

In [52]:
import cv2
import numpy as np

In [117]:
img = cv2.imread('a.jpeg')

In [118]:
img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
img

array([[96, 95, 95, ..., 45, 43, 43],
       [96, 95, 95, ..., 45, 43, 43],
       [92, 92, 92, ..., 44, 44, 44],
       ...,
       [93, 93, 94, ..., 50, 50, 50],
       [39, 39, 39, ..., 50, 50, 50],
       [ 2,  2,  2, ..., 50, 50, 50]], dtype=uint8)

In [119]:
img = cv2.GaussianBlur(img, (5, 5), 0)

In [120]:
_, img = cv2.threshold(img, 33, 255, cv2.THRESH_BINARY_INV)

In [122]:
img = cv2.bitwise_not(img)

In [128]:
img = cv2.imread('o.jpeg')
height, width = img.shape[:2]

In [129]:
desire_wid = 580
aspect = height / width

In [130]:
desire_hght = int(aspect * desire_wid)

In [131]:
resz_img = cv2.resize(img, (desire_wid, desire_hght), interpolation=cv2.INTER_AREA)

In [133]:
shrp_kernel = np.array([[-1, -1, -1],
                        [-1, 9, -1],
                        [-1, -1, -1],
                        ])

In [134]:
shrp_image = cv2.filter2D(resz_img, -1, shrp_kernel)

In [136]:
cv2.imwrite('res.jpeg', img=shrp_image)

True

In [3]:
import sys
import time as t

In [5]:
for i in range(10):
    sys.stdout.write('-' * i)
    t.sleep(1)

---------------------------------------------